export const GAPI_INIT_START = 'GAPI_INIT_START';

export const GOOGLE_AUTH_STATE_CHANGED = 'GOOGLE_AUTH_STATE_CHANGED';

export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS';

export const GOOGLE_SIGN_OUT_START = 'GOOGLE_SIGN_OUT_START';
export const GOOGLE_SIGN_OUT_SUCCESS = 'GOOGLE_SIGN_OUT_SUCCESS';

export const FETCH_ALBUMS_START = 'FETCH_ALBUMS_START';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';

export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';